---
collections:
  - middleware_automation.common

galaxy_info:
  role_name: amq_streams_common
  namespace: middleware_automation
  author: Romain Pelisse
  description: AMQ Streams common plays
  company: Red Hat, Inc.

  license: Apache License 2.0

  min_ansible_version: "2.14"

  platforms:
   - name: EL
     versions:
     - "8"

  galaxy_tags:
    - java
    - jboss
    - wildfly
    - cli
    - server
