---
amq_streams_install_product_version: 3.3.2
amq_streams_install_scala_version: 2.13
amq_streams_install_version: "{{ amq_streams_install_scala_version }}-{{ amq_streams_install_product_version }}"
amq_streams_install_archive_file: "kafka_{{ amq_streams_install_version }}.tgz"
amq_streams_install_download_url: "https://downloads.apache.org/kafka/{{ amq_streams_install_product_version }}/kafka_{{ amq_streams_install_version }}.tgz"
amq_streams_install_download_dir: /opt
amq_streams_install_install_dir: /opt
amq_streams_install_path_to_archive_file: "{{ amq_streams_install_download_dir }}/{{ amq_streams_install_archive_file }}"
amq_streams_install_prereqs_dependencies:
  - tar
amq_streams_install_openjdk_version: 17
amq_streams_install_home: "{{ amq_streams_install_install_dir }}/kafka_{{ amq_streams_install_version }}/"
amq_streams_install_create_topic_script: "{{ amq_streams_install_home }}/bin/kafka-topics.sh"
amq_streams_install_zookeeper_enabled: true
amq_streams_install_zookeeper_config: /etc/amq_streams_zookeeper.properties
amq_streams_install_zookeeper_config_template: templates/zookeeper.properties.j2
amq_streams_install_zookeeper_server_start: "{{ amq_streams_install_home }}/bin/zookeeper-server-start.sh"
amq_streams_install_zookeeper_user: 'amq_streams_zookeeper'
amq_streams_install_zookeeper_group: 'amq_streams'
amq_streams_install_zookeeper_service_name: 'amq_streams_zookeeper'
amq_streams_install_zookeeper_service_config_template: 'templates/service.conf.j2'
amq_streams_install_zookeeper_port: 2181
amq_streams_install_zookeeper_host: 'localhost'
amq_streams_install_zookeeper_data_dir: /tmp/zookeeper
amq_streams_install_zookeeper_logs_dir: "/var/log/{{ amq_streams_install_zookeeper_service_name }}/"
amq_streams_install_zookeeper_max_client_cnxns: 0
amq_streams_install_zookeeper_admin_enable_server: 'false'

amq_streams_install_broker_enabled: true
amq_streams_install_broker_server_start: "{{ amq_streams_install_home }}/bin/kafka-server-start.sh"
amq_streams_install_broker_config: "/etc/amq_streams_broker.properties"
amq_streams_install_broker_service_name: 'amq_streams_broker'
amq_streams_install_broker_user: 'amq_streams_broker'
amq_streams_install_broker_group: 'amq_streams'
amq_streams_install_broker_service_config_template: 'templates/broker.conf.j2'
amq_streams_install_broker_service_config_file: '/etc/broker.conf'
amq_streams_install_broker_logs_dir: "/var/logs/{{ amq_streams_install_broker_service_name }}/"
amq_streams_install_broker_num_network_threads: 3
amq_streams_install_broker_num_io_threads: 8
amq_streams_install_broker_buffer_send_bytes: 102400
amq_streams_install_broker_buffer_bytes: 102400
amq_streams_install_broker_socket_request_max_bytes: 104857600
amq_streams_install_broker_num_partitions: 1
amq_streams_install_broker_num_recovery_threads_per_data_dir: 1
amq_streams_install_broker_offsets_topic_replication_factor: 1
amq_streams_install_broker_transaction_state_log_replication_factor: 1
amq_streams_install_broker_transaction_state_log_min_isr: 1
amq_streams_install_broker_log_retention_hours: 168
amq_streams_install_broker_log_retention_check_interval_ms: 300000
amq_streams_install_broker_zookeeper_connection_timeout_ms: 18000
amq_streams_install_broker_group_initial_rebalance_delay_ms: 0
amq_streams_install_broker_properties_template: templates/server.properties.j2

amq_streams_install_systemd_home: '/usr/lib/systemd/system'
amq_streams_install_systemd_service_config_file_template: 'templates/service_systemd.j2'

amq_streams_install_bootstrap_server_host: localhost
amq_streams_install_bootstrap_server_port: 9092
