---
- name: "Ansible Playbook to install Zookeeper and Broker with Authentication"
  hosts: all
  vars:
    # Enabling Zookeeper Authentication
    amq_streams_zookeeper_auth_enabled: true
    amq_streams_zookeeper_auth_user: zkadmin
    amq_streams_zookeeper_auth_pass: p@ssw0rd

    # Enabling Kafka Broker Listeners
    amq_streams_broker_listeners:
      - AUTHENTICATED://:{{ amq_streams_broker_listener_port }}
      - REPLICATION://:{{ amq_streams_broker_listener_internal_port }}

    # Listener for inter-broker communications
    amq_streams_broker_inter_broker_listener: REPLICATION

    # Enabling Kafka Broker Authentication
    amq_streams_broker_auth_enabled: true
    amq_streams_broker_auth_scram_enabled: true
    amq_streams_broker_auth_listeners:
      - AUTHENTICATED:SASL_PLAINTEXT
      - REPLICATION:PLAINTEXT

    amq_streams_broker_auth_sasl_mechanisms:
      - PLAIN
      - SCRAM-SHA-512

    # Kafka Plain Users
    amq_streams_broker_auth_plain_users:
      - username: admin
        password: p@ssw0rd
      - username: kafkauser
        password: p@ssw0rd

    # Defining default Kafka user for administrative tasks
    amq_streams_broker_admin_mechanism: PLAIN
    #amq_streams_broker_admin_mechanism: SCRAM-SHA-512
    amq_streams_broker_admin_username: admin
    amq_streams_broker_admin_password: p@ssw0rd

    # Topic Management
    amq_streams_broker_topics:
      - name: sampleTopic
        partitions: 1
        replication_factor: 1
      - name: otherTopic
        partitions: 1
        replication_factor: 1
  roles:
    - role: amq_streams_zookeeper
  tasks:
    - name: "Ensure Zookeeper is running and available."
      ansible.builtin.include_role:
        name: amq_streams_zookeeper
      vars:
        amq_streams_common_skip_download: true

    - name: "Ensure Broker is running and available."
      ansible.builtin.include_role:
        name: amq_streams_broker
      vars:
        amq_streams_common_skip_download: true

    - name: "Create topics"
      ansible.builtin.include_role:
        name: amq_streams_broker
        tasks_from: topic/create.yml
      loop: "{{ amq_streams_broker_topics }}"
      loop_control:
        loop_var: topic
      vars:
        topic_name: "{{ topic.name }}"
        topic_partitions: "{{ topic.partitions }}"
        topic_replication_factor: "{{ topic.replication_factor }}"

    - name: "Describe topics"
      ansible.builtin.include_role:
        name: amq_streams_broker
        tasks_from: topic/describe.yml
      loop: "{{ amq_streams_broker_topics }}"
      loop_control:
        loop_var: topic
      vars:
        topic_name: "{{ topic.name }}"

    - name: "Delete topics"
      ansible.builtin.include_role:
        name: amq_streams_broker
        tasks_from: topic/delete.yml
      loop: "{{ amq_streams_broker_topics }}"
      loop_control:
        loop_var: topic
      vars:
        topic_name: "{{ topic.name }}"

  post_tasks:
    - name: "Display numbers of Zookeeper instances managed by Ansible."
      ansible.builtin.debug:
        msg: "Numbers of Zookeeper instances: {{ amq_streams_zookeeper_instance_count }}."
      when:
        - amq_streams_zookeeper_instance_count_enabled is defined and amq_streams_zookeeper_instance_count_enabled

    - name: "Display numbers of broker instances managed by Ansible:"
      ansible.builtin.debug:
        msg: "Numbers of broker instances: {{ amq_streams_broker_instance_count }}."
      when:
        - amq_streams_broker_instance_count_enabled is defined and amq_streams_broker_instance_count_enabled

    - name: "Validate that Zookeeper deployment is functional."
      ansible.builtin.include_role:
        name: amq_streams_zookeeper
        tasks_from: validate.yml

    - name: "Validate that Broker deployment is functional."
      ansible.builtin.include_role:
        name: amq_streams_broker
        tasks_from: validate.yml
